### PR TITLE
Storing property values as an array if a property occurs multiple times

### PR DESCRIPTION
**Pull request by dwolters**
Fixed that problem that if a property occurs multiple times only the value of the last property is being stored. Now, if a property occurs multiple times all values are stored in an array based on the order of apperance.

Fixes the following issue #6

### CODE REVIEW

**Comment by addnab** [comment]
Thank you very much for the PR.

It LGTM. Could you just have the linting errors fixed and have a test case added for this change? And then it should be good to merge.

@Vasanth-Indix @lakshmirajagopalan This needs review. Thanks.

**Comment by Vasanth-Indix** [comment]
Thanks @dwolters for the PR. 
I will test it out for few more micro-data adopted sites and get back in a couple of days.  Meanwhile a test case for the mentioned scenario would be great.

**Comment by dwolters** [comment]
Thanks for having a look at the problem. I added the test case based on the example from schema.org/Recipe. Their JSON-LD looks nearly exactly the JSON-LD created by the extractor. Only exception is that their corresponding JSON-LD does not repeat the \@context property for nested objects if it is the same as the context of the outer object. However, I from my point of view that's a separate issue.

**Comment by Vasanth-Indix** [comment]
Am going ahead and merging the PR.

**Pull request merged**
